<a href="https://colab.research.google.com/github/arzmtva/my-data-analysis/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_%E2%84%963_%E2%80%94_%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [2]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(url)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
X = df.drop("Survived", axis=1)
y = df["Survived"]

print("Размер X:", X.shape)
print("Размер y:", y.shape)

Размер X: (891, 11)
Размер y: (891,)

In [6]:
features = [
    "Pclass",
    "Sex",
    "Age",
    "SibSp",
    "Parch",
    "Fare",
    "Embarked"
]

X = df[features]
y = df["Survived"]

X.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

In [8]:
numeric_features = [
    "Pclass",
    "Age",
    "SibSp",
    "Parch",
    "Fare"
]

categorical_features = [
    "Sex",
    "Embarked"
]

print("Числовые признаки:", numeric_features)
print("Категориальные признаки:", categorical_features)

Числовые признаки: ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']
Категориальные признаки: ['Sex', 'Embarked']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (712, 7)
X_test: (179, 7)
y_train: (712,)
y_test: (179,)

In [10]:
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [11]:
categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

In [12]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [13]:
X_train_transformed = preprocessor.fit_transform(X_train)

X_test_transformed = preprocessor.transform(X_test)

print("Размер train после обработки:", X_train_transformed.shape)
print("Размер test после обработки:", X_test_transformed.shape)

Размер train после обработки: (712, 10)
Размер test после обработки: (179, 10)

In [14]:
preprocessor.fit_transform(X_train)

array([[ 0.82956755, -0.08113533, -0.46508428, ...,  0.        ,
         0.        ,  1.        ],
       [-0.37094484, -0.08113533, -0.46508428, ...,  0.        ,
         0.        ,  1.        ],
       [-1.57145722, -0.08113533, -0.46508428, ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [ 0.82956755,  1.41700669,  0.47833454, ...,  0.        ,
         0.        ,  1.        ],
       [-1.57145722,  1.34017889, -0.46508428, ...,  0.        ,
         0.        ,  1.        ],
       [-1.57145722, -0.08113533, -0.46508428, ...,  0.        ,
         0.        ,  1.        ]])

In [15]:
preprocessor.transform(X_test)

array([[ 0.82956755, -0.42686041,  1.42175336, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.82956755,  1.10969551, -0.46508428, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.82956755, -0.58051601, -0.46508428, ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [-0.37094484, -0.11954923, -0.46508428, ...,  0.        ,
         0.        ,  1.        ],
       [-0.37094484, -0.50368821, -0.46508428, ...,  1.        ,
         0.        ,  0.        ],
       [-0.37094484,  0.11093416,  0.47833454, ...,  0.        ,
         0.        ,  1.        ]])

In [16]:
preprocessor.fit_transform(X_test)

array([[ 0.81887886, -0.3658317 ,  1.08714223, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.81887886,  1.17541866, -0.51449118, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.81887886, -0.51995674, -0.51449118, ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [-0.3632124 , -0.05758163, -0.51449118, ...,  0.        ,
         0.        ,  1.        ],
       [-0.3632124 , -0.44289422, -0.51449118, ...,  1.        ,
         0.        ,  0.        ],
       [-0.3632124 ,  0.17360592,  0.28632553, ...,  0.        ,
         0.        ,  1.        ]])

In [17]:
print("Пропуски в исходном X_train:")
print(X_train.isnull().sum())

print("\nПропуски после обработки:")
print(np.isnan(X_train_transformed.toarray()).sum())

Пропуски в исходном X_train:
Pclass        0
Sex           0
Age         137
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

Пропуски после обработки:

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

In [18]:
print(np.isnan(X_train_transformed).sum())

0

In [19]:
print("Train:", X_train_transformed.shape)
print("Test:", X_test_transformed.shape)

print(
    "Количество признаков одинаковое:",
    X_train_transformed.shape[1] == X_test_transformed.shape[1]
)

Train: (712, 10)
Test: (179, 10)
Количество признаков одинаковое: True

In [20]:
print("Обучение preprocessing выполнено только на X_train:")
print("fit → X_train")
print("transform → X_test")

Обучение preprocessing выполнено только на X_train:
fit → X_train
transform → X_test

In [21]:
model_pipeline = Pipeline(steps=[
    ("preprocessing", preprocessor)
])

In [22]:
X_train_final = model_pipeline.fit_transform(X_train)
X_test_final = model_pipeline.transform(X_test)

print("Train после Pipeline:", X_train_final.shape)
print("Test после Pipeline:", X_test_final.shape)

Train после Pipeline: (712, 10)
Test после Pipeline: (179, 10)

In [23]:
print("=== ФИНАЛЬНАЯ ПРОВЕРКА ===")

print("Размер исходного train:", X_train.shape)
print("Размер исходного test:", X_test.shape)

print("Размер обработанного train:", X_train_final.shape)
print("Размер обработанного test:", X_test_final.shape)

print(
    "Размерность train и test совпадает:",
    X_train_final.shape[1] == X_test_final.shape[1]
)

print(
    "В train нет пропусков:",
    not np.isnan(
        X_train_final.toarray() if hasattr(X_train_final, "toarray") else X_train_final
    ).any()
)

print(
    "В test нет пропусков:",
    not np.isnan(
        X_test_final.toarray() if hasattr(X_test_final, "toarray") else X_test_final
    ).any()
)

=== ФИНАЛЬНАЯ ПРОВЕРКА ===
Размер исходного train: (712, 7)
Размер исходного test: (179, 7)
Размер обработанного train: (712, 10)
Размер обработанного test: (179, 10)
Размерность train и test совпадает: True
В train нет пропусков: True
В test нет пропусков: True